In [10]:
import numpy as np
import pandas as pd
import snowflake.connector
import requests
import io

ModuleNotFoundError: No module named 'snowflake'

In [2]:
conn = snowflake.connector.connect(user='esteban.correa@RAPPI.COM', 
                                   authenticator='externalbrowser', 
                                   account='hg51401', 
                                   warehouse="RP_PERSONALUSER_WH",
                                   database="FIVETRAN")

Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
Going to open: https://fs.security.rappi.com/adfs/ls?SAMLRequest=jZJBT%2BMwEIX%2FSuQ9J07StAKrKSq0LNECW2hgpb25sVMsHDvrcRraX4%2BTtBJ7AHGz7Pf8zcyb6cVbJb0dNyC0SlEUhMjjqtBMqG2KnvJr%2Fwx5YKliVGrFU7TngC5mU6CVrMm8sS%2Fqkf9rOFjPfaSAdA8paowimoIAomjFgdiCrOd3tyQOQkIBuLEOh44WBsKxXqytCcZt2wbtKNBmi%2BMwDHF4jp2qk%2FxAHxD114zaaKsLLU%2BWN9fTJ4gIh0mHcApHWB2Nl0INI%2FiKshlEQG7yfOWvfq9z5M1P3V1pBU3FzZqbnSj40%2BPtUAC4Cm5%2BjqMkjAJQui0lfeWFrurGur8Cd8IlZ1jqrXATyhYpql8FOzzo%2FM%2B%2ByQ91xu7Er8m4XOySjb7MyvPNgbF4eb%2BrkuW4ypcPBfKeT3nGXZ4ZQMMz1aVo3VUYJ3448qMoj2IympDRODibTP4ib%2BFSFIra3nkqtYQAeNEYYfeBoXUt%2BgopKwFLQMMikJ5gZt9rb4o%2Feo6bdO%2BGmy1WWopi711rU1H7%2BeyjIOpvBPPLXkp4RYWcM2Y4gMtASt1eGU6tW1hrGo7wbKD%2Bv7Kzdw%3D%3D&RelayState=50489 to authenticate...

# Forecast Kampos 175

In [3]:
forecast1 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (175)"""

In [4]:
df_forecast1 = pd.read_sql(forecast1, conn)
df_forecast1.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\2158886200.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast1 = pd.read_sql(forecast1, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [5]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Kampos-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast1.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Kampos-11-03-2024.xlsx" creado con éxito.

# Forecast Kompro 158

In [6]:
forecast2 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (158)"""

In [7]:
df_forecast2 = pd.read_sql(forecast2, conn)
df_forecast2.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\4065911811.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast2 = pd.read_sql(forecast2, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [8]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Grisales-Escobar-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast2.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Grisales-Escobar-11-03-2024.xlsx" creado con éxito.

# Forecast EXCOL  160

In [9]:
forecast3 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (160)"""

In [10]:
df_forecast3 = pd.read_sql(forecast3, conn)
df_forecast3.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\794855713.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast3 = pd.read_sql(forecast3, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [11]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-excol-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast3.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-excol-11-03-2024.xlsx" creado con éxito.

# Forecast WARUWA  162

In [12]:
forecast4 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (162)"""

In [13]:
df_forecast4 = pd.read_sql(forecast4, conn)
df_forecast4.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\630455612.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast4 = pd.read_sql(forecast4, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [14]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Waruwa-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast4.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Waruwa-11-03-2024.xlsx" creado con éxito.

# Forecast DON FRUVER  193

In [15]:
forecast5 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (193)"""

In [16]:
df_forecast5 = pd.read_sql(forecast5, conn)
df_forecast5.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\845904481.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast5 = pd.read_sql(forecast5, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [17]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Don-Fruver-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast5.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Don-Fruver-11-03-2024.xlsx" creado con éxito.

# Forecast Frusander 163

In [18]:
forecast6 = """SELECT CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_1 as Lunes, FORECAST_2 as Martes, FORECAST_3 as Miercoles, FORECAST_4 as Jueves, FORECAST_5 as Viernes, FORECAST_6 as Sabado, FORECAST_7 as Domingo, FORECAST_8 as Lunes_1, FORECAST_9 as Martes_1, FORECAST_10 as Miercoles_1, FORECAST_11 as Jueves_1
from fivetran.turbo_turbo_supply.roq_direct_supply_sync  
where country = 'CO' 
AND date = CURRENT_DATE() - INTERVAL '1 DAY'
  AND IS_PO_DAY = 'true'
AND provider_id IN (163)"""

In [19]:
df_forecast6 = pd.read_sql(forecast6, conn)
df_forecast6.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\3604858673.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast6 = pd.read_sql(forecast6, conn)

Empty DataFrame
Columns: [CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_1, JUEVES_1]
Index: []

In [20]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Frusander-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast6.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Frusander-11-03-2024.xlsx" creado con éxito.

# Forecast Kampos 175 Cartagena

In [21]:
forecast7 = """SELECT DATE, CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_3 as Lunes, FORECAST_4 as Martes, FORECAST_5 as Miercoles, FORECAST_6 as Jueves, FORECAST_7 as Sabado, FORECAST_8 as Domingo, FORECAST_9 as Lunes_1, FORECAST_10 as Martes_1, FORECAST_11 as Miercoles_, FORECAST_12 as Jueves_
from fivetran.turbo_turbo_supply.roq_direct_supply_sync 
where country = 'CO' 
AND DATE = CURRENT_DATE - INTERVAL '3 DAY'
  AND IS_PO_DAY = 'true'
  AND provider_id IN (175)
  AND WAREHOUSE_ID IN ( 3,5,6,7)"""

In [22]:
df_forecast7 = pd.read_sql(forecast7, conn)
df_forecast7.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\2058565215.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast7 = pd.read_sql(forecast7, conn)

,DATE,CITY,WAREHOUSE,RETAIL_ID,PRODUCT_NAME,LUNES,MARTES,MIERCOLES,JUEVES,SABADO,DOMINGO,LUNES_1,MARTES_1,MIERCOLES_,JUEVES_
0,2024-03-08,Cartagena,Mar Del Norte,12349,Tomate Tipo Uvalina EC Peq - Experiencia Colom...,0.333333,0.333333,0.0,0.0,0.0,0.0,0.0,0.333333,0.333333,0.0
1,2024-03-08,Cartagena,Mar Del Norte,12552,Papa Sababenra Mini EC 500gr - Experiencia Col...,0.000000,0.000000,0.0,0.0,0.5,0.0,0.0,0.000000,0.000000,0.0

In [23]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Kampos-Cartagena-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast7.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Kampos-Cartagena-11-03-2024.xlsx" creado con éxito.

In [24]:
forecast8 = """SELECT DATE, CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, FORECAST_3 as Lunes, FORECAST_4 as Martes, FORECAST_5 as Miercoles, FORECAST_6 as Jueves, FORECAST_7 as Sabado, FORECAST_8 as Domingo, FORECAST_9 as Lunes_1, FORECAST_10 as Martes_1, FORECAST_11 as Miercoles_, FORECAST_12 as Jueves_
from fivetran.turbo_turbo_supply.roq_direct_supply_sync 
where country = 'CO' 
AND DATE = CURRENT_DATE - INTERVAL '3 DAY'
  AND IS_PO_DAY = 'true'
  AND provider_id IN (330)
  """

In [25]:
df_forecast8 = pd.read_sql(forecast8, conn)
df_forecast8.head(2)

C:\Users\marcel.kempe\AppData\Local\Temp\ipykernel_34484\2022079472.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_forecast8 = pd.read_sql(forecast8, conn)

Empty DataFrame
Columns: [DATE, CITY, WAREHOUSE, RETAIL_ID, PRODUCT_NAME, LUNES, MARTES, MIERCOLES, JUEVES, SABADO, DOMINGO, LUNES_1, MARTES_1, MIERCOLES_, JUEVES_]
Index: []

In [26]:
import pandas as pd
from datetime import datetime, timedelta

# Simulación de lectura de datos desde SQL (reemplaza con tu propio código)
# df_forecast1 = pd.read_sql(forecast1, conn)

# Crear una fecha actual formateada
fecha_actual = datetime.now().date()

# Crear un DataFrame con las fechas en las filas, comenzando desde fecha_actual + 1
num_columnas = 7
columnas_fechas = [(fecha_actual + timedelta(days=i + 1)).strftime('%d-%m-%Y') for i in range(num_columnas)]
df_fechas = pd.DataFrame({'Fechas': columnas_fechas})

# Crear un archivo de Excel con el nombre personalizado
nombre_archivo = f'Forecast-Distrifruver-{fecha_actual.strftime("%d-%m-%Y")}.xlsx'

# Crear un escritor de Excel
with pd.ExcelWriter(nombre_archivo, engine='xlsxwriter') as writer:
    # Transponer el DataFrame de fechas para que estén en filas
    df_fechas = df_fechas.transpose()
    
    # Escribir los datos del DataFrame de fechas en la hoja 'Sheet1' desde la fila 1, empezando desde la columna F (índice 5)
    df_fechas.to_excel(writer, sheet_name='Sheet1', startrow=0, startcol=4, header=False)
    
    # Escribir los datos del DataFrame en la hoja 'Sheet1' desde la fila 2
    df_forecast8.to_excel(writer, sheet_name='Sheet1', startrow=1, index=False)

print(f'Archivo de Excel "{nombre_archivo}" creado con éxito.')

Archivo de Excel "Forecast-Distrifruver-11-03-2024.xlsx" creado con éxito.